CREATE DATABASE IF NOT EXISTS hacktues;

USE hacktues;

CREATE TABLE IF NOT EXISTS Users (
    UserID BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
    Name VARCHAR(50) NOT NULL,
    Password VARCHAR(60) NOT NULL,
    PRIMARY KEY(UserID)
);

CREATE TABLE IF NOT EXISTS Devices (
    DeviceID BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
    MACAddress CHAR(17) NOT NULL,
    IPAddress VARCHAR(15) NOT NULL,
    Name VARCHAR(50) NOT NULL,
    Temperature FLOAT NOT NULL,
    Temp_Threshold FLOAT NOT NULL,
    Humidity FLOAT NOT NULL,
    Hum_Threshold FLOAT NOT NULL,
    Methane INT NOT NULL,
    C02 INT NOT NULL,
    PRIMARY KEY(DeviceID)
);

CREATE TABLE IF NOT EXISTS UsersDevices (
    UserID BIGINT UNSIGNED NOT NULL,
    DeviceID BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY(UserID, DeviceID),
    FOREIGN KEY (UserID) REFERENCES Users(UserID),
    FOREIGN KEY (DeviceID) REFERENCES Devices(DeviceID)
) 