// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RootAndRot.Server.Data;

#nullable disable

namespace RootAndRot.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("latin1_swedish_ci")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "latin1");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RootAndRot.Server.Data.Device", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("DeviceID")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<int>("C02")
                        .HasColumnType("int(11)");

                    b.Property<float>("HumThreshold")
                        .HasColumnType("float")
                        .HasColumnName("Hum_Threshold");

                    b.Property<float>("Humidity")
                        .HasColumnType("float");

                    b.Property<string>("Ipaddress")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("IPAddress");

                    b.Property<string>("Macaddress")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("char(17)")
                        .HasColumnName("MACAddress")
                        .IsFixedLength();

                    b.Property<int>("Methane")
                        .HasColumnType("int(11)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<float>("TempThreshold")
                        .HasColumnType("float")
                        .HasColumnName("Temp_Threshold");

                    b.Property<float>("Temperature")
                        .HasColumnType("float");

                    b.HasKey("DeviceId")
                        .HasName("PRIMARY");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("RootAndRot.Server.Data.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("UserID")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("UserId")
                        .HasName("PRIMARY");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UsersDevice", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("UserID");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("DeviceID");

                    b.HasKey("UserId", "DeviceId")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "DeviceId" }, "DeviceID");

                    b.ToTable("UsersDevices", (string)null);
                });

            modelBuilder.Entity("UsersDevice", b =>
                {
                    b.HasOne("RootAndRot.Server.Data.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .IsRequired()
                        .HasConstraintName("UsersDevices_ibfk_2");

                    b.HasOne("RootAndRot.Server.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("UsersDevices_ibfk_1");
                });
#pragma warning restore 612, 618
        }
    }
}
